# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/oms/Orders.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/oms/Orders.proto", :syntax => :proto3) do
    add_message "oms.Order" do
      optional :id, :uint32, 1
      optional :number, :string, 2
      optional :total, :float, 3
    end
    add_message "oms.GetOrderReq" do
      optional :id, :uint32, 1
    end
    add_message "oms.GetOrderResp" do
      optional :order, :message, 1, "oms.Order"
    end
    add_message "oms.GetOrdersReq" do
      optional :search, :string, 1
      optional :limit, :uint32, 2
    end
    add_message "oms.CreateOrdersResp" do
      repeated :orders, :message, 1, "oms.Order"
    end
  end
end

module Oms
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oms.Order").msgclass
  GetOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oms.GetOrderReq").msgclass
  GetOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oms.GetOrderResp").msgclass
  GetOrdersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oms.GetOrdersReq").msgclass
  CreateOrdersResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("oms.CreateOrdersResp").msgclass
end
