# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/oms/Orders.proto for package 'oms'

require 'grpc'
require 'proto/oms/Orders_pb'

module Oms
  module Orders
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'oms.Orders'

      # Demonstrates a request response call
      rpc :GetOrder, ::Oms::GetOrderReq, ::Oms::GetOrderResp
      # Demonstrates a server streamer call
      rpc :GetOrders, ::Oms::GetOrdersReq, stream(::Oms::Order)
      # Demonstrates a client streaming call
      rpc :CreateOrders, stream(::Oms::Order), ::Oms::CreateOrdersResp
      # Demonstrates a bidirectional streaming call
      rpc :CreateOrdersInStream, stream(::Oms::Order), stream(::Oms::Order)
    end

    Stub = Service.rpc_stub_class
  end
end
