# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/pim/Products.proto for package 'pim'

require 'grpc'
require 'proto/pim/Products_pb'

module Pim
  module Products
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pim.Products'

      # Demonstrates a request response call
      rpc :GetProduct, ::Pim::GetProductReq, ::Pim::GetProductResp
      # Demonstrates a server streamer call
      rpc :GetProducts, ::Pim::GetProductsReq, stream(::Pim::Product)
      # Demonstrates a client streaming call
      rpc :CreateProducts, stream(::Pim::Product), ::Pim::CreateProductsResp
      # Demonstrates a bidirectional streaming call
      rpc :CreateProductsInStream, stream(::Pim::Product), stream(::Pim::Product)
    end

    Stub = Service.rpc_stub_class
  end
end
