# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pim/Users.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/pim/Users.proto", :syntax => :proto3) do
    add_message "pim.User" do
      optional :id, :uint32, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
      optional :email, :string, 4
      optional :seller_id, :uint32, 5
      optional :oms_user_id, :uint32, 6
      optional :active, :bool, 7
      optional :shard_id, :uint32, 8
    end
    add_message "pim.GetUserReq" do
      optional :id, :uint32, 1
    end
    add_message "pim.GetUserResp" do
      optional :user, :message, 1, "pim.User"
    end
    add_message "pim.CreateUserResp" do
      optional :user, :message, 1, "pim.User"
      optional :error_message, :string, 2
    end
    add_message "pim.GetUsersReq" do
      optional :search, :string, 1
      optional :limit, :uint32, 2
    end
  end
end

module Pim
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pim.User").msgclass
  GetUserReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pim.GetUserReq").msgclass
  GetUserResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pim.GetUserResp").msgclass
  CreateUserResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pim.CreateUserResp").msgclass
  GetUsersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pim.GetUsersReq").msgclass
end
