# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/connect_service/IntegrationCalls.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/connect_service/IntegrationCalls.proto", :syntax => :proto3) do
    add_message "rpc.connect_service.GetIntegrationCallReq" do
      optional :marketplace, :string, 1
      optional :method, :string, 2
      optional :config, :string, 3
      optional :payload, :string, 4
    end
    add_message "rpc.connect_service.GetIntegrationCallResp" do
      optional :response, :string, 1
      optional :resp_metadata, :string, 2
    end
  end
end

module Rpc
  module ConnectService
    GetIntegrationCallReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetIntegrationCallReq").msgclass
    GetIntegrationCallResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetIntegrationCallResp").msgclass
  end
end
