# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/IntegrationCalls.proto for package 'connect_service'

require 'grpc'
require 'proto/connect_service/IntegrationCalls_pb'

module ConnectService
  module IntegrationCalls
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'connect_service.IntegrationCalls'

      # Demonstrates a request response call
      rpc :GetIntegrationCall, ::ConnectService::GetIntegrationCallReq, ::ConnectService::GetIntegrationCallResp
    end

    Stub = Service.rpc_stub_class
  end
end
