# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/Marketplaces.proto for package 'rpc.connect_service'

require 'grpc'
require 'proto/connect_service/Marketplaces_pb'

module Rpc
  module ConnectService
    module Marketplaces
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'rpc.connect_service.Marketplaces'

        # Demonstrates a request response call
        rpc :GetMarketplace, ::Rpc::ConnectService::GetMarketplaceReq, ::Rpc::ConnectService::GetMarketplaceResp
        # Demonstrates a server streamer call
        rpc :GetMarketplaces, ::Rpc::ConnectService::GetMarketplacesReq, stream(::Rpc::ConnectService::Marketplace)
        # Demonstrates a client streaming call
        rpc :CreateMarketplaces, stream(::Rpc::ConnectService::Marketplace), ::Rpc::ConnectService::CreateMarketplacesResp
        # Demonstrates a bidirectional streaming call
        rpc :CreateMarketplacesInStream, stream(::Rpc::ConnectService::Marketplace), stream(::Rpc::ConnectService::Marketplace)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
