# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/connect_service/Marketplaces.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/connect_service/Marketplaces.proto", :syntax => :proto3) do
    add_message "rpc.connect_service.Marketplace" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      optional :code, :string, 3
      optional :active, :bool, 4
    end
    add_message "rpc.connect_service.GetMarketplaceReq" do
      optional :id, :uint32, 1
      optional :search, :string, 2
    end
    add_message "rpc.connect_service.GetMarketplaceResp" do
      optional :marketplace, :message, 1, "rpc.connect_service.Marketplace"
    end
    add_message "rpc.connect_service.GetMarketplacesReq" do
      optional :search, :string, 1
      optional :limit, :uint32, 2
    end
    add_message "rpc.connect_service.CreateMarketplacesResp" do
      repeated :marketplaces, :message, 1, "rpc.connect_service.Marketplace"
    end
  end
end

module Rpc
  module ConnectService
    Marketplace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.Marketplace").msgclass
    GetMarketplaceReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetMarketplaceReq").msgclass
    GetMarketplaceResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetMarketplaceResp").msgclass
    GetMarketplacesReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetMarketplacesReq").msgclass
    CreateMarketplacesResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.CreateMarketplacesResp").msgclass
  end
end
