# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/Marketplaces.proto for package 'connect_service'

require 'grpc'
require 'proto/connect_service/Marketplaces_pb'

module ConnectService
  module Marketplaces
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'connect_service.Marketplaces'

      # Demonstrates a request response call
      rpc :GetMarketplace, ::ConnectService::GetMarketplaceReq, ::ConnectService::GetMarketplaceResp
      # Demonstrates a server streamer call
      rpc :GetMarketplaces, ::ConnectService::GetMarketplacesReq, stream(::ConnectService::Marketplace)
      # Demonstrates a client streaming call
      rpc :CreateMarketplaces, stream(::ConnectService::Marketplace), ::ConnectService::CreateMarketplacesResp
      # Demonstrates a bidirectional streaming call
      rpc :CreateMarketplacesInStream, stream(::ConnectService::Marketplace), stream(::ConnectService::Marketplace)
    end

    Stub = Service.rpc_stub_class
  end
end
