# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/Sellers.proto for package 'rpc.connect_service'

require 'grpc'
require 'proto/connect_service/Sellers_pb'

module Rpc
  module ConnectService
    module Sellers
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'rpc.connect_service.Sellers'

        # Demonstrates a request response call
        rpc :GetSeller, ::Rpc::ConnectService::GetSellerReq, ::Rpc::ConnectService::GetSellerResp
        # Demonstrates a server streamer call
        rpc :GetSellers, ::Rpc::ConnectService::GetSellersReq, stream(::Rpc::ConnectService::Seller)
        # Demonstrates a client streaming call
        rpc :CreateSellers, stream(::Rpc::ConnectService::Seller), ::Rpc::ConnectService::CreateSellersResp
        # Demonstrates a bidirectional streaming call
        rpc :CreateSellersInStream, stream(::Rpc::ConnectService::Seller), stream(::Rpc::ConnectService::Seller)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
