# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/SellerMarketplaces.proto for package 'rpc.connect_service'

require 'grpc'
require 'proto/connect_service/SellerMarketplaces_pb'

module Rpc
  module ConnectService
    module SellerMarketplaces
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'rpc.connect_service.SellerMarketplaces'

        # Demonstrates a request response call
        rpc :GetSellerMarketplace, ::Rpc::ConnectService::GetSellerMarketplaceReq, ::Rpc::ConnectService::GetSellerMarketplaceResp
        # Demonstrates a server streamer call
        rpc :GetSellerMarketplaces, ::Rpc::ConnectService::GetSellerMarketplacesReq, stream(::Rpc::ConnectService::SellerMarketplace)
        # Demonstrates a client streaming call
        rpc :CreateSellerMarketplaces, stream(::Rpc::ConnectService::SellerMarketplace), ::Rpc::ConnectService::CreateSellerMarketplacesResp
        # Demonstrates a bidirectional streaming call
        rpc :CreateSellerMarketplacesInStream, stream(::Rpc::ConnectService::SellerMarketplace), stream(::Rpc::ConnectService::SellerMarketplace)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
