# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/SellerMarketplaces.proto for package 'connect_service'

require 'grpc'
require 'proto/connect_service/SellerMarketplaces_pb'

module ConnectService
  module SellerMarketplaces
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'connect_service.SellerMarketplaces'

      # Demonstrates a request response call
      rpc :GetSellerMarketplace, ::ConnectService::GetSellerMarketplaceReq, ::ConnectService::GetSellerMarketplaceResp
      # Demonstrates a server streamer call
      rpc :GetSellerMarketplaces, ::ConnectService::GetSellerMarketplacesReq, stream(::ConnectService::SellerMarketplace)
      # Demonstrates a client streaming call
      rpc :CreateSellerMarketplaces, stream(::ConnectService::SellerMarketplace), ::ConnectService::CreateSellerMarketplacesResp
      # Demonstrates a bidirectional streaming call
      rpc :CreateSellerMarketplacesInStream, stream(::ConnectService::SellerMarketplace), stream(::ConnectService::SellerMarketplace)
    end

    Stub = Service.rpc_stub_class
  end
end
