# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/connect_service/Sellers.proto for package 'connect_service'

require 'grpc'
require 'proto/connect_service/Sellers_pb'

module ConnectService
  module Sellers
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'connect_service.Sellers'

      # Demonstrates a request response call
      rpc :GetSeller, ::ConnectService::GetSellerReq, ::ConnectService::GetSellerResp
      # Demonstrates a server streamer call
      rpc :GetSellers, ::ConnectService::GetSellersReq, stream(::ConnectService::Seller)
      # Demonstrates a client streaming call
      rpc :CreateSellers, stream(::ConnectService::Seller), ::ConnectService::CreateSellersResp
      # Demonstrates a bidirectional streaming call
      rpc :CreateSellersInStream, stream(::ConnectService::Seller), stream(::ConnectService::Seller)
    end

    Stub = Service.rpc_stub_class
  end
end
