# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/connect_service/SellerMarketplaces.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/connect_service/SellerMarketplaces.proto", :syntax => :proto3) do
    add_message "rpc.connect_service.SellerMarketplace" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      optional :ss_code, :string, 3
      optional :seller_id, :uint32, 4
      optional :marketplace_id, :uint32, 5
      optional :active, :bool, 6
      optional :state, :string, 7
      optional :store_split_order_enabled, :bool, 8
      optional :sync_status, :string, 9
      optional :mp_timezone, :string, 10
      optional :currency_code, :string, 11
      optional :store_code, :string, 12
      optional :order_routing_rule, :string, 13
      optional :marketplace_seller_id, :string, 14
      optional :last_error, :string, 15
    end
    add_message "rpc.connect_service.GetSellerMarketplaceReq" do
      optional :id, :uint32, 1
    end
    add_message "rpc.connect_service.GetSellerMarketplaceResp" do
      optional :seller_marketplace, :message, 1, "rpc.connect_service.SellerMarketplace"
    end
    add_message "rpc.connect_service.GetSellerMarketplacesReq" do
      optional :search, :string, 1
      optional :limit, :uint32, 2
    end
    add_message "rpc.connect_service.CreateSellerMarketplacesResp" do
      repeated :seller_marketplaces, :message, 1, "rpc.connect_service.SellerMarketplace"
    end
  end
end

module Rpc
  module ConnectService
    SellerMarketplace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.SellerMarketplace").msgclass
    GetSellerMarketplaceReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetSellerMarketplaceReq").msgclass
    GetSellerMarketplaceResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetSellerMarketplaceResp").msgclass
    GetSellerMarketplacesReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.GetSellerMarketplacesReq").msgclass
    CreateSellerMarketplacesResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.connect_service.CreateSellerMarketplacesResp").msgclass
  end
end
